---
- name: Execute command
  hosts: localhost
  gather_facts: no
  vars:
    path: desktop.json

  tasks:
    - name: Check the file exists
      stat:
        path: "{{ path }}"
      register: stat_result

    - debug:
        var: stat_result

    - name: Complain if the file doesn't exist
      fail:
        msg: "We need file {{ path }}"
      when:
        - not stat_result.stat.exists

    - name: Print output from file
      debug: msg="the content of the file is {{ lookup('file', '{{ path }}') }}"
      when:
        - stat_result.stat.exists